//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprioriSelf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentSubmission
    {
        public int Id { get; set; }
        public int AssessmentId { get; set; }
        public int LearnerId { get; set; }
        public string FileType { get; set; }
        public System.DateTime SubmissionTime { get; set; }
        public string FilePath { get; set; }
        public string Learner_Username { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        public virtual User User { get; set; }
    }
}
