//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprioriSelf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assessment()
        {
            this.AssessmentEvaluations = new HashSet<AssessmentEvaluation>();
            this.AssessmentSubmissions = new HashSet<AssessmentSubmission>();
        }
    
        public int AssessmentID { get; set; }
        public string AssessmentTitle { get; set; }
        public System.DateTime DateTime { get; set; }
        public System.DateTime DueDate { get; set; }
        public int Points { get; set; }
        public string FileType { get; set; }
        public string Note { get; set; }
        public Nullable<int> OfferedCourse_OfferedCourseID { get; set; }
        public string FilePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentEvaluation> AssessmentEvaluations { get; set; }
        public virtual OfferedCours OfferedCours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentSubmission> AssessmentSubmissions { get; set; }
    }
}
