//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprioriSelf.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExistingDataFromWeb : DbContext
    {
        public ExistingDataFromWeb()
            : base("name=ExistingDataFromWeb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AssessmentEvaluation> AssessmentEvaluations { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<AssessmentSubmission> AssessmentSubmissions { get; set; }
        public virtual DbSet<CourseCategory> CourseCategories { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Extra> Extras { get; set; }
        public virtual DbSet<IsAttempted> IsAttempteds { get; set; }
        public virtual DbSet<LearnerEnroll> LearnerEnrolls { get; set; }
        public virtual DbSet<LectureResource> LectureResources { get; set; }
        public virtual DbSet<LectureSchedule> LectureSchedules { get; set; }
        public virtual DbSet<OfferedCours> OfferedCourses { get; set; }
        public virtual DbSet<QuizAttempt> QuizAttempts { get; set; }
        public virtual DbSet<QuizQuestion> QuizQuestions { get; set; }
        public virtual DbSet<Quiz> Quizs { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
