//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprioriSelf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearnerEnroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LearnerEnroll()
        {
            this.AssessmentEvaluations = new HashSet<AssessmentEvaluation>();
        }
    
        public int LearnerEnrollID { get; set; }
        public System.DateTime EnrollDate { get; set; }
        public System.DateTime CompletionDate { get; set; }
        public short Status { get; set; }
        public string EnrolledLearnerID { get; set; }
        public Nullable<int> EnrolledCourse_OfferedCourseID { get; set; }
        public string EnrolledLearner_Username { get; set; }
        public int EnrolledCourseID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentEvaluation> AssessmentEvaluations { get; set; }
        public virtual OfferedCours OfferedCours { get; set; }
        public virtual User User { get; set; }
    }
}
