//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprioriSelf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LectureResource
    {
        public int LectureResourceID { get; set; }
        public string FileName { get; set; }
        public string ResourceType { get; set; }
        public System.DateTime DateTime { get; set; }
        public int LectureScheduleID { get; set; }
        public string FilePath { get; set; }
    
        public virtual LectureSchedule LectureSchedule { get; set; }
    }
}
