//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprioriSelf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LectureSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LectureSchedule()
        {
            this.LectureResources = new HashSet<LectureResource>();
        }
    
        public int LectureScheduleID { get; set; }
        public System.DateTime LectureDate { get; set; }
        public System.TimeSpan LectureTime { get; set; }
        public string StreamName { get; set; }
        public int OfferedCourseID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LectureResource> LectureResources { get; set; }
        public virtual OfferedCours OfferedCours { get; set; }
    }
}
