//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprioriSelf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferedCours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfferedCours()
        {
            this.Assessments = new HashSet<Assessment>();
            this.LearnerEnrolls = new HashSet<LearnerEnroll>();
            this.LectureSchedules = new HashSet<LectureSchedule>();
            this.QuizAttempts = new HashSet<QuizAttempt>();
        }
    
        public int OfferedCourseID { get; set; }
        public System.DateTime StartingDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public decimal CreditHours { get; set; }
        public string Course_CourseCode { get; set; }
        public string OfferdBy_Username { get; set; }
        public string OfferedByID { get; set; }
        public int LearnerCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assessment> Assessments { get; set; }
        public virtual Cours Cours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LearnerEnroll> LearnerEnrolls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LectureSchedule> LectureSchedules { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizAttempt> QuizAttempts { get; set; }
    }
}
