//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprioriSelf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestion
    {
        public string QuestionStatement { get; set; }
        public string Options { get; set; }
        public string Answer { get; set; }
        public int QuizID { get; set; }
        public int ID { get; set; }
    
        public virtual Quiz Quiz { get; set; }
    }
}
