//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprioriSelf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public int RuleID { get; set; }
        public double Confidence { get; set; }
        public string Drivers { get; set; }
        public string Indicates { get; set; }
    }
}
